trustly:
  private-key: src/main/resources/keys/trustly_private_key.pem
  public-key: src/main/resources/keys/trustly_public_key.pem
  api-url: https://test.trustly.com/api/1
  api-username: devcode
  api-password: change_this_gef4D37ypL
  success-url: http://bambora-code-test-lc.herokuapp.com/success
  fail-url: http://bambora-code-test-lc.herokuapp.com/failure
  notification-url: http://bambora-code-test-lc.herokuapp.com/notifications/a2b63j23dj23883jhfhfh